* Academic Website Template
** Note about modifying your website
    There are two ways to modify your website. Each has pros and 
    cons and require using different tools. You should make you decision
    based on how comfortable you feel with the tools required for 
    each option, but most importantly, how likely you are to use
    them for other things. It may not be useful to learn a new tool
    if you're only going to use it once. 

    The two options are using GitHub's webpage or using Git locally. I
    discuss them very briefly below to help you make your decision.

**** Modify the website online
     You can use Github's webpage to modify your website. This is
     the easiest method and may very well suit your needs. You won't have 
     to install additional software and can modify your website from any
     computer or device (e.g., tablet) without worrying much about anything
     else. However, you won't be able to preview the changes to your website
     before making them public. 

     If you don't know what Git is or you are not interested in programming,
     then this may be the best option for you.

**** Modify the website on your computer
     This option requires installing a few software and learning to use 
     them. You will also need to learn to use a 
     text editor (e.g., [[https://www.spacemacs.org/][spacemacs]] [my favorite :) ], [[https://www.vim.org/][vim]], [[https://atom.io/][atom]], [[https://notepad-plus-plus.org/][notepad]])

     This requires installing the following software:
      - [[https://www.ruby-lang.org/en/documentation/installation/][Ruby]] 
      - [[https://jekyllrb.com/docs/][Jekyll]]
      - [[https://git-scm.com/book/en/v2/Getting-Started-Installing-Git][Git]]
      - Text editor (many computers have at least one installed by default)
     
     After you have installed the required software, you need to [[https://guides.github.com/activities/forking/#clone][Clone]] this
     repo to your computer. You should now be able to modify add content
     to your website.
    
     After making changes, preview them on your local computer following this
     [[https://jekyllrb.com/docs/][guide]]. To make your changes public, you have to push them to GitHub using
     Git.

** Other useful resources
   - [[http://svmiller.com/blog/2015/08/create-your-website-in-jekyll/][Create your Academic Website in Jekyll and Host it on Github]]

